export default {
  name: 'Keep it Simple',
  props: {
    theme: {
      primaryColor: '#333',
      secondaryColor: '#333',
      appMenuButtonBackgroundColor: '#fcfcfc',
      appMenuBarBurgerColor: '#333',
      appMenuBarBurgerHoverColor: '#000',
      appMenuDrawerBurgerColor: '#333',
      appMenuDrawerBurgerHoverColor: '#000',
      textFontFamily: 'sans-serif',
      headerFontFamily: 'sans-serif',
      sectionMarkerNumberColor: '#fff',
      sectionMarkerBackgroundColor: '#fff',
      campaignFormTextColor: '#fcfcfc',
      campaignFormButtonBackgroundColor: '#fcfcfc',
      footerBackgroundColor: '#fcfcfc',
      baseFontSize: '16px',
      textLineHeight: 2,
      linkStyle: 'basic',
      linkColor: '#777',
      disableElevation: true,
      surfaceBackgroundColor: '#fcfcfc',
      callToActionButtonBackgroundColor: '#fcfcfc',
    },
  },
  default: true,
};
