export default {
  name: 'Soft Pink',
  props: {
    theme: {
      primaryColor: '#FFCFE2',
      secondaryColor: '#FFECF0',
      textFontFamily: 'Verdana, Geneva, sans-serif',
      headerFontFamily: 'Palatino, serif',
      textColor: '#444444',
      iconColor: '#444444',
      headingColor: '#FFCFE2',
      backgroundColor: '#FFF8FA',
      surfaceBackgroundColor: '#FFECF0',
      surfaceBorderRadius: '5px',
      insightBackgroundColor: '#FFECF0',
      insightTextColor: '#FFCFE2',
      pullquoteBackgroundColor: '#FFECF0',
      callToActionBackgroundColor: '#FFECF0',
      callToActionButtonColor: '#FFCFE2',
      sectionMarkerBackgroundColor: '#FFECF0',
      sectionMarkerNumberColor: '#444444',
      sectionMarkerTextColor: '#FFCFE2',
      sectionMarkerTitleColor: '#FFCFE2',
      sectionMarkerNumberOpacity: 1,
      landingSectionBackgroundColor: '#FFECF0',
      landingSectionArrowColor: '#FFECF0',
      landingSectionTitleBackgroundColor: '#FFECF0',
      landingSectionGradientColor: 'rgba(255, 225, 225, 0.3)',
    },
  },
};
