name: CI

on: ["push", "pull_request"]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Test
      run: |
        npx yarn
        npx yarn test
      env:
        CI: true
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
  publish:
    if: github.ref == 'refs/heads/master'
    needs: [test]
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Release
      run: |
        echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        npx yarn
        npm run release
      env:
        CI: true
        NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
